default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  J01:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0
  J12:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0
  J23:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0
  J34:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0
  J45:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0
  J56:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_accleration: 0