Panels:
  - Class: rviz_common/Displays
    Name: Displays
Displays:
  - Class: rviz_default_plugins/RobotModel
    Enabled: true
    Name: RobotModel
    Description Topic: robot_description
  - Class: rviz_default_plugins/Image
    Enabled: true
    Name: Camera
    Topic: /rgb_camera/image_raw