controller_names:
  - joint_state_broadcaster
  - arm_controller

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - J01
    - J12
    - J23
    - J34
    - J45
    - J56
