controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - J01
      - J12
      - J23
      - J34
      - J45
      - J56
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
    
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
